## BERCHMANS KEVIN 



## ``Department of Data Science - Data and Visual Analytics Lab``

# ``Numpy & Pandas``

## `Import CSV file into DataFrames and Preprocess that dataset`

# Numpy

In [1]:
import numpy as np

In [2]:
bk=np.genfromtxt("CA_01 Assignment-(215229107).csv",delimiter=',',dtype=str,skip_header=0)  

In [3]:
bk

array([['S.No', 'Name', 'Gender', 'Age', 'Weight', 'Height'],
       ['1', 'Muhammad Fernado Ganesan K', 'Male', '85', '87', '190'],
       ['2', 'Berchmans S', 'Male', '23', '80', '180'],
       ['3', 'Jacksparrow P', 'Male', '62', '', '168'],
       ['4', 'Mia Elizabeth Ruby D ', 'Female', '20', '56', ''],
       ['5', 'Catherine Lolita G', 'Female', '30', '53', '150'],
       ['6', 'Johny Depp T', 'Male', '54', '110', '159'],
       ['7', 'Velan R', 'Male', '13', '28', '140'],
       ['8', 'Jothika Jancy W', 'Female', '43', '88', '164'],
       ['9', 'Vimalkan G', 'Male', '65', '95', '175'],
       ['10', 'Devi T', 'Female', '19', '60', '146'],
       ['11', 'Priya V', 'Female', '68', '100', '190'],
       ['12', 'Jaya Surya F', 'Male', '90', '61', '205'],
       ['13', 'Andrew Princily B', 'Female', '28', '45', '185'],
       ['14', 'Zafir E', 'Male', '36', '72', '175'],
       ['15', 'Jafar David Murugan A', 'Male', '110', '70', '180'],
       ['16', 'Lily Jasmin Durga I', 'Female

#### Size

In [4]:
np.shape(bk)

(36, 6)

#### Data rows here

In [5]:
np.shape(bk)[0]

36

#### Data columns here

In [6]:
np.shape(bk)[1]

6

#### Dimensions

In [7]:
bk.ndim

2

In [8]:
np.ndim(bk)

2

#### Type

In [9]:
type(bk)

numpy.ndarray

#### DataType

In [10]:
bk.dtype

dtype('<U26')

#### Show top 6 rows

In [11]:
bk[:5]

array([['S.No', 'Name', 'Gender', 'Age', 'Weight', 'Height'],
       ['1', 'Muhammad Fernado Ganesan K', 'Male', '85', '87', '190'],
       ['2', 'Berchmans S', 'Male', '23', '80', '180'],
       ['3', 'Jacksparrow P', 'Male', '62', '', '168'],
       ['4', 'Mia Elizabeth Ruby D ', 'Female', '20', '56', '']],
      dtype='<U26')

#### Select first 3 items in 4th column

In [12]:
bk[:3,3]

array(['Age', '85', '23'], dtype='<U26')

#### Select first item in first all column

In [13]:
bk[0,:]

array(['S.No', 'Name', 'Gender', 'Age', 'Weight', 'Height'], dtype='<U26')

#### Show 3rd Row

In [14]:
bk[2]

array(['2', 'Berchmans S', 'Male', '23', '80', '180'], dtype='<U26')

#### Show 1st Column

In [15]:
bk[:,0]

array(['S.No', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
       '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33',
       '34', '35'], dtype='<U26')

#### Show 2nd Column

In [16]:
bk[:,1]

array(['Name', 'Muhammad Fernado Ganesan K', 'Berchmans S',
       'Jacksparrow P', 'Mia Elizabeth Ruby D ', 'Catherine Lolita G',
       'Johny Depp T', 'Velan R', 'Jothika Jancy W', 'Vimalkan G',
       'Devi T', 'Priya V', 'Jaya Surya F', 'Andrew Princily B',
       'Zafir E', 'Jafar David Murugan A', 'Lily Jasmin Durga I',
       'Victoria Rani N', 'Karthikeyan L', 'Diya Aruna K',
       'Amala Santhiya S', 'Mei Mohan R', 'Nitra Meena H',
       'Edwin Starjan D', 'Divya Bharadhi M', 'Deepika Mary R',
       'Ezhil Manna Frindo U', 'Infant Ismail Hasan J', 'Jerlin Jepa F',
       'Alex Anto C', 'Joni Santhosh Raj J', 'Esther Mary S',
       'Julian Kural Ovien K ', 'Pushpa O', 'Antony Manibal Shareef B',
       'Dinesh Kumar R'], dtype='<U26')

#### Show 3rd Column

In [17]:
bk[:,2]

array(['Gender', 'Male', 'Male', 'Male', 'Female', 'Female', 'Male',
       'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female',
       'Male', 'Male', 'Female', 'Female', 'Male', 'Female', 'Female',
       'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male',
       'Male'], dtype='<U26')

#### Show 4th Column

In [18]:
bk[:,3]

array(['Age', '85', '23', '62', '20', '30', '54', '13', '43', '65', '19',
       '68', '90', '28', '36', '110', '35', '58', '44', '34', '59', '25',
       '70', '12', '27', '75', '95', '115', '35', '25', '27', '23', '26',
       '31', '28', '80'], dtype='<U26')

#### Show 5th Column

In [19]:
bk[:,4]

array(['Weight', '87', '80', '', '56', '53', '110', '28', '88', '95',
       '60', '100', '61', '45', '72', '70', '110', '87', '150', '130',
       '87', '76', '57', '32', '60', '49', '113', '90', '69', '97', '79',
       '73', '89', '77', '118', '96'], dtype='<U26')

#### Shoe 6th Column

In [20]:
bk[:,5]

array(['Height', '190', '180', '168', '', '150', '159', '140', '164',
       '175', '146', '190', '205', '185', '175', '180', '199', '173',
       '130', '197', '180', '176', '217', '130', '169', '147', '189',
       '174', '160', '190', '179', '189', '198', '189', '220', '190'],
      dtype='<U26')

#### Show top 1 to 14 rows

In [21]:
bk[1:,:][:14,:]

array([['1', 'Muhammad Fernado Ganesan K', 'Male', '85', '87', '190'],
       ['2', 'Berchmans S', 'Male', '23', '80', '180'],
       ['3', 'Jacksparrow P', 'Male', '62', '', '168'],
       ['4', 'Mia Elizabeth Ruby D ', 'Female', '20', '56', ''],
       ['5', 'Catherine Lolita G', 'Female', '30', '53', '150'],
       ['6', 'Johny Depp T', 'Male', '54', '110', '159'],
       ['7', 'Velan R', 'Male', '13', '28', '140'],
       ['8', 'Jothika Jancy W', 'Female', '43', '88', '164'],
       ['9', 'Vimalkan G', 'Male', '65', '95', '175'],
       ['10', 'Devi T', 'Female', '19', '60', '146'],
       ['11', 'Priya V', 'Female', '68', '100', '190'],
       ['12', 'Jaya Surya F', 'Male', '90', '61', '205'],
       ['13', 'Andrew Princily B', 'Female', '28', '45', '185'],
       ['14', 'Zafir E', 'Male', '36', '72', '175']], dtype='<U26')

#### Select entire array

In [22]:
bk[:]

array([['S.No', 'Name', 'Gender', 'Age', 'Weight', 'Height'],
       ['1', 'Muhammad Fernado Ganesan K', 'Male', '85', '87', '190'],
       ['2', 'Berchmans S', 'Male', '23', '80', '180'],
       ['3', 'Jacksparrow P', 'Male', '62', '', '168'],
       ['4', 'Mia Elizabeth Ruby D ', 'Female', '20', '56', ''],
       ['5', 'Catherine Lolita G', 'Female', '30', '53', '150'],
       ['6', 'Johny Depp T', 'Male', '54', '110', '159'],
       ['7', 'Velan R', 'Male', '13', '28', '140'],
       ['8', 'Jothika Jancy W', 'Female', '43', '88', '164'],
       ['9', 'Vimalkan G', 'Male', '65', '95', '175'],
       ['10', 'Devi T', 'Female', '19', '60', '146'],
       ['11', 'Priya V', 'Female', '68', '100', '190'],
       ['12', 'Jaya Surya F', 'Male', '90', '61', '205'],
       ['13', 'Andrew Princily B', 'Female', '28', '45', '185'],
       ['14', 'Zafir E', 'Male', '36', '72', '175'],
       ['15', 'Jafar David Murugan A', 'Male', '110', '70', '180'],
       ['16', 'Lily Jasmin Durga I', 'Female

#### Iterating Arrays Using nditer()

In [23]:
for q in np.nditer(bk):
    print(q)

S.No
Name
Gender
Age
Weight
Height
1
Muhammad Fernado Ganesan K
Male
85
87
190
2
Berchmans S
Male
23
80
180
3
Jacksparrow P
Male
62

168
4
Mia Elizabeth Ruby D 
Female
20
56

5
Catherine Lolita G
Female
30
53
150
6
Johny Depp T
Male
54
110
159
7
Velan R
Male
13
28
140
8
Jothika Jancy W
Female
43
88
164
9
Vimalkan G
Male
65
95
175
10
Devi T
Female
19
60
146
11
Priya V
Female
68
100
190
12
Jaya Surya F
Male
90
61
205
13
Andrew Princily B
Female
28
45
185
14
Zafir E
Male
36
72
175
15
Jafar David Murugan A
Male
110
70
180
16
Lily Jasmin Durga I
Female
35
110
199
17
Victoria Rani N
Female
58
87
173
18
Karthikeyan L
Male
44
150
130
19
Diya Aruna K
Female
34
130
197
20
Amala Santhiya S
Female
59
87
180
21
Mei Mohan R
Male
25
76
176
22
Nitra Meena H
Female
70
57
217
23
Edwin Starjan D
Male
12
32
130
24
Divya Bharadhi M
Female
27
60
169
25
Deepika Mary R
Female
75
49
147
26
Ezhil Manna Frindo U
Male
95
113
189
27
Infant Ismail Hasan J
Male
115
90
174
28
Jerlin Jepa F
Female
35
69
160
29
Alex An

#### 1 Dimensional Numpy Arrays
   #### Select 5th row all columns and show it's 4th value

In [24]:
q1 = bk[4,:]

In [25]:
q1

array(['4', 'Mia Elizabeth Ruby D ', 'Female', '20', '56', ''],
      dtype='<U26')

In [26]:
q1[3]

'20'

#### Convert to Integer values and Show

In [27]:
q2 = bk[5,4].astype(int)

In [28]:
q2

53

#### Vectorization Operations

#### Missing Values

In [29]:
q4 = bk[3,:]

q5 = bk[4,:]

#### Fill the missing values

In [30]:
q6 = bk[3,4] = 90

In [31]:
q6

90

In [32]:
q7 = bk[4,-1] = 182

In [33]:
q7

182

#### Display the q4 qnd q5

In [34]:
q4

array(['3', 'Jacksparrow P', 'Male', '62', '90', '168'], dtype='<U26')

In [35]:
q5

array(['4', 'Mia Elizabeth Ruby D ', 'Female', '20', '56', '182'],
      dtype='<U26')

##### Aggregate Functions

In [36]:
bk[1:,3:].astype('int')

array([[ 85,  87, 190],
       [ 23,  80, 180],
       [ 62,  90, 168],
       [ 20,  56, 182],
       [ 30,  53, 150],
       [ 54, 110, 159],
       [ 13,  28, 140],
       [ 43,  88, 164],
       [ 65,  95, 175],
       [ 19,  60, 146],
       [ 68, 100, 190],
       [ 90,  61, 205],
       [ 28,  45, 185],
       [ 36,  72, 175],
       [110,  70, 180],
       [ 35, 110, 199],
       [ 58,  87, 173],
       [ 44, 150, 130],
       [ 34, 130, 197],
       [ 59,  87, 180],
       [ 25,  76, 176],
       [ 70,  57, 217],
       [ 12,  32, 130],
       [ 27,  60, 169],
       [ 75,  49, 147],
       [ 95, 113, 189],
       [115,  90, 174],
       [ 35,  69, 160],
       [ 25,  97, 190],
       [ 27,  79, 179],
       [ 23,  73, 189],
       [ 26,  89, 198],
       [ 31,  77, 189],
       [ 28, 118, 220],
       [ 80,  96, 190]])

In [37]:
bk[1:,3:].astype('int').max()

220

In [38]:
bk[1:,3:].astype('int').min()

12

In [39]:
bk[1:,3:].astype('int').mean()

101.8

In [40]:
bk[1:,3:].astype('int').mean(axis=0)

array([ 47.71428571,  80.97142857, 176.71428571])

In [41]:
bk[1:,3:].astype('int').mean(axis=1).shape

(35,)

In [42]:
bk[1:,3:].astype('int').mean(axis=1)

array([120.66666667,  94.33333333, 106.66666667,  86.        ,
        77.66666667, 107.66666667,  60.33333333,  98.33333333,
       111.66666667,  75.        , 119.33333333, 118.66666667,
        86.        ,  94.33333333, 120.        , 114.66666667,
       106.        , 108.        , 120.33333333, 108.66666667,
        92.33333333, 114.66666667,  58.        ,  85.33333333,
        90.33333333, 132.33333333, 126.33333333,  88.        ,
       104.        ,  95.        ,  95.        , 104.33333333,
        99.        , 122.        , 122.        ])

In [43]:
bk[1:,3:].astype('int').mean(axis=1).shape

(35,)

In [44]:
np.median(bk[1:,3:].astype('int'))

88.0

In [45]:
bk[1:,3:].astype('int').std()

60.239901346912205

#### Transpose

In [46]:
bk[:,3:].transpose()

array([['Age', '85', '23', '62', '20', '30', '54', '13', '43', '65',
        '19', '68', '90', '28', '36', '110', '35', '58', '44', '34',
        '59', '25', '70', '12', '27', '75', '95', '115', '35', '25',
        '27', '23', '26', '31', '28', '80'],
       ['Weight', '87', '80', '90', '56', '53', '110', '28', '88', '95',
        '60', '100', '61', '45', '72', '70', '110', '87', '150', '130',
        '87', '76', '57', '32', '60', '49', '113', '90', '69', '97',
        '79', '73', '89', '77', '118', '96'],
       ['Height', '190', '180', '168', '182', '150', '159', '140', '164',
        '175', '146', '190', '205', '185', '175', '180', '199', '173',
        '130', '197', '180', '176', '217', '130', '169', '147', '189',
        '174', '160', '190', '179', '189', '198', '189', '220', '190']],
      dtype='<U26')

In [47]:
np.transpose(bk).shape

(6, 36)

#### NumPy Array Comparisons 

In [48]:
bk[1:,3:].astype(int) > 100

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False,  True,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False,  True],
       [False,  True,  True],
       [False, False,  True],
       [False,  True,  True],
       [False,  True,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False,  True,  True],
       [ True, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [Fa

In [49]:
bk[1:,3:].astype(int) > 55

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [False, False,  True],
       [False,  True,  True],
       [False, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False, False,  True],
       [False,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [Fa

In [50]:
bk[1:,3:].astype(int) < 55

array([[False, False, False],
       [ True, False, False],
       [False, False, False],
       [ True, False, False],
       [ True,  True, False],
       [ True, False, False],
       [ True,  True, False],
       [ True, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True, False],
       [ True, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [ True, False, False],
       [ True, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [ True,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ T

In [51]:
bk[1:,3:].astype(int) < 100

array([[ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True, False, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True, False, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True,  True, False],
       [ True, False, False],
       [ True, False, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True, False, False],
       [False,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ True,  True, False],
       [ T

#### Convert wines data into 1D array 

In [52]:
bk.ravel()

array(['S.No', 'Name', 'Gender', 'Age', 'Weight', 'Height', '1',
       'Muhammad Fernado Ganesan K', 'Male', '85', '87', '190', '2',
       'Berchmans S', 'Male', '23', '80', '180', '3', 'Jacksparrow P',
       'Male', '62', '90', '168', '4', 'Mia Elizabeth Ruby D ', 'Female',
       '20', '56', '182', '5', 'Catherine Lolita G', 'Female', '30', '53',
       '150', '6', 'Johny Depp T', 'Male', '54', '110', '159', '7',
       'Velan R', 'Male', '13', '28', '140', '8', 'Jothika Jancy W',
       'Female', '43', '88', '164', '9', 'Vimalkan G', 'Male', '65', '95',
       '175', '10', 'Devi T', 'Female', '19', '60', '146', '11',
       'Priya V', 'Female', '68', '100', '190', '12', 'Jaya Surya F',
       'Male', '90', '61', '205', '13', 'Andrew Princily B', 'Female',
       '28', '45', '185', '14', 'Zafir E', 'Male', '36', '72', '175',
       '15', 'Jafar David Murugan A', 'Male', '110', '70', '180', '16',
       'Lily Jasmin Durga I', 'Female', '35', '110', '199', '17',
       'Victoria Ran

In [53]:
bk.ravel().shape

(216,)

#### Sort Column Ascendind Order

In [54]:
np.sort(bk[1:,3:])

array([['190', '85', '87'],
       ['180', '23', '80'],
       ['168', '62', '90'],
       ['182', '20', '56'],
       ['150', '30', '53'],
       ['110', '159', '54'],
       ['13', '140', '28'],
       ['164', '43', '88'],
       ['175', '65', '95'],
       ['146', '19', '60'],
       ['100', '190', '68'],
       ['205', '61', '90'],
       ['185', '28', '45'],
       ['175', '36', '72'],
       ['110', '180', '70'],
       ['110', '199', '35'],
       ['173', '58', '87'],
       ['130', '150', '44'],
       ['130', '197', '34'],
       ['180', '59', '87'],
       ['176', '25', '76'],
       ['217', '57', '70'],
       ['12', '130', '32'],
       ['169', '27', '60'],
       ['147', '49', '75'],
       ['113', '189', '95'],
       ['115', '174', '90'],
       ['160', '35', '69'],
       ['190', '25', '97'],
       ['179', '27', '79'],
       ['189', '23', '73'],
       ['198', '26', '89'],
       ['189', '31', '77'],
       ['118', '220', '28'],
       ['190', '80', '96']], dtype='<U2

#### Make sorting to take place in-place 

In [55]:
bk[1:,3:].sort()

In [56]:
 bk[1:,3:]

array([['190', '85', '87'],
       ['180', '23', '80'],
       ['168', '62', '90'],
       ['182', '20', '56'],
       ['150', '30', '53'],
       ['110', '159', '54'],
       ['13', '140', '28'],
       ['164', '43', '88'],
       ['175', '65', '95'],
       ['146', '19', '60'],
       ['100', '190', '68'],
       ['205', '61', '90'],
       ['185', '28', '45'],
       ['175', '36', '72'],
       ['110', '180', '70'],
       ['110', '199', '35'],
       ['173', '58', '87'],
       ['130', '150', '44'],
       ['130', '197', '34'],
       ['180', '59', '87'],
       ['176', '25', '76'],
       ['217', '57', '70'],
       ['12', '130', '32'],
       ['169', '27', '60'],
       ['147', '49', '75'],
       ['113', '189', '95'],
       ['115', '174', '90'],
       ['160', '35', '69'],
       ['190', '25', '97'],
       ['179', '27', '79'],
       ['189', '23', '73'],
       ['198', '26', '89'],
       ['189', '31', '77'],
       ['118', '220', '28'],
       ['190', '80', '96']], dtype='<U2

#### Save and Load 

In [57]:
np.save('Berchmans_Numpy',bk)

In [58]:
c = np.load('Berchmans_Numpy.npy')
c

array([['S.No', 'Name', 'Gender', 'Age', 'Weight', 'Height'],
       ['1', 'Muhammad Fernado Ganesan K', 'Male', '190', '85', '87'],
       ['2', 'Berchmans S', 'Male', '180', '23', '80'],
       ['3', 'Jacksparrow P', 'Male', '168', '62', '90'],
       ['4', 'Mia Elizabeth Ruby D ', 'Female', '182', '20', '56'],
       ['5', 'Catherine Lolita G', 'Female', '150', '30', '53'],
       ['6', 'Johny Depp T', 'Male', '110', '159', '54'],
       ['7', 'Velan R', 'Male', '13', '140', '28'],
       ['8', 'Jothika Jancy W', 'Female', '164', '43', '88'],
       ['9', 'Vimalkan G', 'Male', '175', '65', '95'],
       ['10', 'Devi T', 'Female', '146', '19', '60'],
       ['11', 'Priya V', 'Female', '100', '190', '68'],
       ['12', 'Jaya Surya F', 'Male', '205', '61', '90'],
       ['13', 'Andrew Princily B', 'Female', '185', '28', '45'],
       ['14', 'Zafir E', 'Male', '175', '36', '72'],
       ['15', 'Jafar David Murugan A', 'Male', '110', '180', '70'],
       ['16', 'Lily Jasmin Durga I', 'F

## Pandas

In [59]:
import pandas as pd

In [60]:
bk_29 = pd.read_csv("CA_01 Assignment-(215229107).csv")
bk_29

S.No                        Name  Gender  Age  Weight  Height
0      1  Muhammad Fernado Ganesan K    Male   85    87.0   190.0
1      2                 Berchmans S    Male   23    80.0   180.0
2      3               Jacksparrow P    Male   62     NaN   168.0
3      4       Mia Elizabeth Ruby D   Female   20    56.0     NaN
4      5          Catherine Lolita G  Female   30    53.0   150.0
5      6                Johny Depp T    Male   54   110.0   159.0
6      7                     Velan R    Male   13    28.0   140.0
7      8             Jothika Jancy W  Female   43    88.0   164.0
8      9                  Vimalkan G    Male   65    95.0   175.0
9     10                      Devi T  Female   19    60.0   146.0
10    11                     Priya V  Female   68   100.0   190.0
11    12                Jaya Surya F    Male   90    61.0   205.0
12    13           Andrew Princily B  Female   28    45.0   185.0
13    14                     Zafir E    Male   36    72.0   175.0
14    15       Jafar David Murugan A    Male  110    70.0   180.0
15    16         Lily Jasmin Durga I  Female   35   110.0   199.0
16    17             Victoria Rani N  Female   58    87.0   173.0
17    18               Karthikeyan L    Male   44   150.0   130.0
18    19                Diya Aruna K  Female   34   130.0   197.0
19    20            Amala Santhiya S  Female   59    87.0   180.0
20    21                 Mei Mohan R    Male   25    76.0   176.0
21    22               Nitra Meena H  Female   70    57.0   217.0
22    23             Edwin Starjan D    Male   12    32.0   130.0
23    24            Divya Bharadhi M  Female   27    60.0   169.0
24    25              Deepika Mary R  Female   75    49.0   147.0
25    26        Ezhil Manna Frindo U    Male   95   113.0   189.0
26    27       Infant Ismail Hasan J    Male  115    90.0   174.0
27    28               Jerlin Jepa F  Female   35    69.0   160.0
28    29                 Alex Anto C    Male   25    97.0   190.0
29    30         Joni Santhosh Raj J    Male   27    79.0   179.0
30    31               Esther Mary S  Female   23    73.0   189.0
31    32       Julian Kural Ovien K     Male   26    89.0   198.0
32    33                    Pushpa O  Female   31    77.0   189.0
33    34    Antony Manibal Shareef B    Male   28   118.0   220.0
34    35              Dinesh Kumar R    Male   80    96.0   190.0

In [61]:
bk_29.head()

S.No                        Name  Gender  Age  Weight  Height
0     1  Muhammad Fernado Ganesan K    Male   85    87.0   190.0
1     2                 Berchmans S    Male   23    80.0   180.0
2     3               Jacksparrow P    Male   62     NaN   168.0
3     4       Mia Elizabeth Ruby D   Female   20    56.0     NaN
4     5          Catherine Lolita G  Female   30    53.0   150.0

In [62]:
bk_29.size

210

In [63]:
bk_29.shape

(35, 6)

In [64]:
bk_29.columns

Index(['S.No', 'Name', 'Gender', 'Age', 'Weight', 'Height'], dtype='object')

In [65]:
bk_29.info

<bound method DataFrame.info of     S.No                        Name  Gender  Age  Weight  Height
0      1  Muhammad Fernado Ganesan K    Male   85    87.0   190.0
1      2                 Berchmans S    Male   23    80.0   180.0
2      3               Jacksparrow P    Male   62     NaN   168.0
3      4       Mia Elizabeth Ruby D   Female   20    56.0     NaN
4      5          Catherine Lolita G  Female   30    53.0   150.0
5      6                Johny Depp T    Male   54   110.0   159.0
6      7                     Velan R    Male   13    28.0   140.0
7      8             Jothika Jancy W  Female   43    88.0   164.0
8      9                  Vimalkan G    Male   65    95.0   175.0
9     10                      Devi T  Female   19    60.0   146.0
10    11                     Priya V  Female   68   100.0   190.0
11    12                Jaya Surya F    Male   90    61.0   205.0
12    13           Andrew Princily B  Female   28    45.0   185.0
13    14                     Zafir E    Male

In [66]:
bk_29.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   S.No    35 non-null     int64  
 1   Name    35 non-null     object 
 2   Gender  35 non-null     object 
 3   Age     35 non-null     int64  
 4   Weight  34 non-null     float64
 5   Height  34 non-null     float64
dtypes: float64(2), int64(2), object(2)
memory usage: 1.8+ KB


In [67]:
bk_29.describe()

S.No         Age      Weight      Height
count  35.000000   35.000000   34.000000   34.000000
mean   18.000000   47.714286   80.705882  176.558824
std    10.246951   28.181733   26.870655   22.082752
min     1.000000   12.000000   28.000000  130.000000
25%     9.500000   26.500000   60.250000  165.000000
50%    18.000000   35.000000   79.500000  179.500000
75%    26.500000   66.500000   95.750000  190.000000
max    35.000000  115.000000  150.000000  220.000000

In [68]:
bk_29.isnull

<bound method DataFrame.isnull of     S.No                        Name  Gender  Age  Weight  Height
0      1  Muhammad Fernado Ganesan K    Male   85    87.0   190.0
1      2                 Berchmans S    Male   23    80.0   180.0
2      3               Jacksparrow P    Male   62     NaN   168.0
3      4       Mia Elizabeth Ruby D   Female   20    56.0     NaN
4      5          Catherine Lolita G  Female   30    53.0   150.0
5      6                Johny Depp T    Male   54   110.0   159.0
6      7                     Velan R    Male   13    28.0   140.0
7      8             Jothika Jancy W  Female   43    88.0   164.0
8      9                  Vimalkan G    Male   65    95.0   175.0
9     10                      Devi T  Female   19    60.0   146.0
10    11                     Priya V  Female   68   100.0   190.0
11    12                Jaya Surya F    Male   90    61.0   205.0
12    13           Andrew Princily B  Female   28    45.0   185.0
13    14                     Zafir E    Ma

In [69]:
bk_29.isnull().sum()

S.No      0
Name      0
Gender    0
Age       0
Weight    1
Height    1
dtype: int64

In [70]:
bk_29.isnull().values.sum()

2

In [71]:
e = bk_29.bfill(axis=0)
e

S.No                        Name  Gender  Age  Weight  Height
0      1  Muhammad Fernado Ganesan K    Male   85    87.0   190.0
1      2                 Berchmans S    Male   23    80.0   180.0
2      3               Jacksparrow P    Male   62    56.0   168.0
3      4       Mia Elizabeth Ruby D   Female   20    56.0   150.0
4      5          Catherine Lolita G  Female   30    53.0   150.0
5      6                Johny Depp T    Male   54   110.0   159.0
6      7                     Velan R    Male   13    28.0   140.0
7      8             Jothika Jancy W  Female   43    88.0   164.0
8      9                  Vimalkan G    Male   65    95.0   175.0
9     10                      Devi T  Female   19    60.0   146.0
10    11                     Priya V  Female   68   100.0   190.0
11    12                Jaya Surya F    Male   90    61.0   205.0
12    13           Andrew Princily B  Female   28    45.0   185.0
13    14                     Zafir E    Male   36    72.0   175.0
14    15       Jafar David Murugan A    Male  110    70.0   180.0
15    16         Lily Jasmin Durga I  Female   35   110.0   199.0
16    17             Victoria Rani N  Female   58    87.0   173.0
17    18               Karthikeyan L    Male   44   150.0   130.0
18    19                Diya Aruna K  Female   34   130.0   197.0
19    20            Amala Santhiya S  Female   59    87.0   180.0
20    21                 Mei Mohan R    Male   25    76.0   176.0
21    22               Nitra Meena H  Female   70    57.0   217.0
22    23             Edwin Starjan D    Male   12    32.0   130.0
23    24            Divya Bharadhi M  Female   27    60.0   169.0
24    25              Deepika Mary R  Female   75    49.0   147.0
25    26        Ezhil Manna Frindo U    Male   95   113.0   189.0
26    27       Infant Ismail Hasan J    Male  115    90.0   174.0
27    28               Jerlin Jepa F  Female   35    69.0   160.0
28    29                 Alex Anto C    Male   25    97.0   190.0
29    30         Joni Santhosh Raj J    Male   27    79.0   179.0
30    31               Esther Mary S  Female   23    73.0   189.0
31    32       Julian Kural Ovien K     Male   26    89.0   198.0
32    33                    Pushpa O  Female   31    77.0   189.0
33    34    Antony Manibal Shareef B    Male   28   118.0   220.0
34    35              Dinesh Kumar R    Male   80    96.0   190.0

In [72]:
e.isnull().values.sum()

0

## Normalization

In [73]:
from sklearn.preprocessing import MinMaxScaler

norm1 = MinMaxScaler()

norm1.fit_transform(e[['Height','Weight']])

array([[0.66666667, 0.48360656],
       [0.55555556, 0.42622951],
       [0.42222222, 0.2295082 ],
       [0.22222222, 0.2295082 ],
       [0.22222222, 0.20491803],
       [0.32222222, 0.67213115],
       [0.11111111, 0.        ],
       [0.37777778, 0.49180328],
       [0.5       , 0.54918033],
       [0.17777778, 0.26229508],
       [0.66666667, 0.59016393],
       [0.83333333, 0.2704918 ],
       [0.61111111, 0.13934426],
       [0.5       , 0.36065574],
       [0.55555556, 0.3442623 ],
       [0.76666667, 0.67213115],
       [0.47777778, 0.48360656],
       [0.        , 1.        ],
       [0.74444444, 0.83606557],
       [0.55555556, 0.48360656],
       [0.51111111, 0.39344262],
       [0.96666667, 0.23770492],
       [0.        , 0.03278689],
       [0.43333333, 0.26229508],
       [0.18888889, 0.17213115],
       [0.65555556, 0.69672131],
       [0.48888889, 0.50819672],
       [0.33333333, 0.33606557],
       [0.66666667, 0.56557377],
       [0.54444444, 0.41803279],
       [0.